Create/Get/Index Events
mbta/parking_lpr pull request #2
Opened 2021-05-03 18:23 UTC by manny-m

In the future this would include Asana ticket.

2021-05-03 20:54 UTC, arkadyan requested changes
This looks great, nice work!

I included a couple of suggestions and a couple of "learning Elixir" tips. Of the suggestions, I think https://github.com/mbta/parking_lpr/pull/2/files#diff-a35793bf58c7ef598e1d4ae43d52917a41cea9c53df5b8b76ec7c498509041d7R7 and https://github.com/mbta/parking_lpr/pull/2/files#diff-919f34789e21d638db68703e81b0a89e8ce15bbfa9b414c73bc48701913f69ecR41 are the two that feel most important to me.

2021-05-03 20:54 UTC, arkadyan commented on lib/parking_lpr/event.ex
> +    _-> nil
Is there a reason to swallow the error here? If you returned it, it would give the caller more information about what went wrong. You could even consider returning whatever `Repo.insert` returns directly—that might make it easier for the [`case` statement](https://github.com/mbta/parking_lpr/pull/2/files#diff-4e6329cb936671affbe9758ccb5256648ce0fcbff5d79ea7984e6c93a977a122R28) to match on `{:ok, event}` vs `{:error, changeset}`.

2021-05-03 20:54 UTC, arkadyan commented on test/parking_lpr/event_test.exs
> +      assert nil === Event.add_event("this is not json","")
`==` is generally the standard operator to use in Elixir.

2021-05-03 20:54 UTC, arkadyan commented on test/parking_lpr/event_test.exs
> +      assert e.data["lorem"] === "ipsum"
This is totally good. I'm just using it as a handy place to throw out another optional approach, which probably seems a little weird and "Elixir-y" at first. But you could do something equivalent using pattern matching, like:

`assert %Event{data: %{"lorem" => "ipsum"}} = Event.add_event(@valid_json, "some_source")`

(If that seems interesting I thought these [free lessons](https://thinkingelixir.com/available-courses/pattern-matching/) were really good.)

2021-05-03 20:54 UTC, arkadyan commented on test/parking_lpr/event_test.exs
> +      assert e.id === hd(Event.list_event_ids())
This doesn't actually hit `get_event`. Maybe it could be something along the lines of `assert Event.get_event(e.id) == e`?

2021-05-03 20:54 UTC, arkadyan commented on lib/parking_lpr_web/controllers/api_controller.ex
> +    })
```suggestion
    event_ids = Event.list_event_ids()
    json(conn, %{
      count: length(event_ids),
      events: event_ids
    })
```

Getting the count from the DB is great for when it saves you from having to retrieve all the records. In this case though you are already pulling all the IDs, so something like the above would let you just count them in code and save a second (granted, tiny) DB call.

2021-05-03 20:54 UTC, arkadyan commented on test/parking_lpr_web/controllers/api_controller_test.exs
> +    data: Jason.encode(%{test: "data"}) |> elem(1),
```suggestion
    data: %{test: "data"} |> Jason.encode() |> elem(1),
```

This is super nitpicky, but there's an Elixir convention to start pipe chains with the first argument to the first function. I think maybe the idea is something like you start with some data, and then each function in the chain transforms it.

2021-05-04 10:50 UTC, paulswartz commented
Another set of helpful resources might be the tickets I worked with Kayla on for scaffolding for Project Draft: https://app.asana.com/0/1199987702860136/list

It includes some additional things even before getting the code running, like static analysis and type checking, as well as having a CI pipeline.

2021-05-04 19:10 UTC, manny-m commented on priv/repo/migrations/20210422163812_create_events.exs
> +      add :source, :string
Thanks for highlighting this! Decided to only `timestamp` required. 

There is a ticket in the future that may change this entire migration based on a recent meeting with stakeholders.

2021-05-04 19:25 UTC, manny-m commented
Ready for re-review @arkadyan 
Latest commit should address the comments you had. Most notably changed error handling to return more useful information.

2021-05-04 20:25 UTC, arkadyan approved these changes
Looks great 👍

2021-05-04 20:25 UTC, arkadyan commented on priv/repo/migrations/20210422163812_create_events.exs
> +      add :source, :string
👌 You might want to remove the other two from [`validate_required`](https://github.com/mbta/parking_lpr/pull/2/files#diff-c4066d1c8294b560dc0615ab560e777a323770ff12f02e86ea53711232563f15R31) to match.

2021-05-04 20:41 UTC, merged